// jon klein, jtklein@alaska.edu
// pshifter calibration file for board c
// automatically generated by nshifter_cal.py

#define PHASE_MAX 360// degrees
#define PHASE_MIN 0// degrees
#define PHASE_STEP 5// degrees
#define PCAL_FREQ 2450// MHz
#define PHASE_INIT -13 // degrees
const uint16_t dac_table[40] = {0, 150, 270, 380, 460, 550, 610, 670, 730, 770, 810, 850, 890, 920, 950, 980, 1010, 1040, 1070, 1090, 1120, 1150, 1180, 1210, 1230, 1260, 1290, 1320, 1340, 1380, 1400, 1430, 1450, 1490, 1520, 1550, 1580, 1610, 1640, 1680};
const uint16_t att_table[40] = {4.0, 3.0, 3.0, 3.0, 2.0, 2.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0};
